server.port=8080
spring.application.name=api-gateway

# 1. Route sang Auth Service (Cổng 8081)
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# 2. Route sang Course Service (Cổng 8082)
spring.cloud.gateway.routes[1].id=course-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/courses/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[1].filters[1]=AuthenticationFilter

# 3. Route sang Registration Service (Cổng 8083) - Test Case 6
spring.cloud.gateway.routes[2].id=registration-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/registrations/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[2].filters[1]=AuthenticationFilter

# 4. Route Public Partner API (Cổng 8082) - Test Case 7 & 8
spring.cloud.gateway.routes[3].id=public-course-service
spring.cloud.gateway.routes[3].uri=http://localhost:8082
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/public/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[3].filters[1]=ApiKeyFilter

jwt.secret=CRS-Microservices-Secret-Key-Nam-3-Hoc-Ky-2026-Doi-Trong-Thuc-Te